# Generated by Django 5.1.6 on 2025-02-13 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Languege',
                'db_table': 'languege',
            },
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.languege')),
            ],
            options={
                'verbose_name_plural': 'Translate',
                'db_table': 'translate',
            },
        ),
    ]
