# Generated by Django 5.1.6 on 2025-02-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languege',
            new_name='Language',
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='translate',
            options={'verbose_name_plural': 'Translates'},
        ),
    ]
