# Generated by Django 5.1.6 on 2025-03-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_rename_languege_language_alter_language_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='Languege',
        ),
        migrations.AlterModelOptions(
            name='languege',
            options={'verbose_name_plural': 'Languege'},
        ),
        migrations.AlterModelOptions(
            name='translate',
            options={'verbose_name_plural': 'Translate'},
        ),
    ]
